---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master 
  labels:
    app: khulnasoft
    role: khulnasoft_cluster_master
    tier: management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khulnasoft
      role: khulnasoft_cluster_master
      tier: management
  template:
    metadata:
      labels:
        app: khulnasoft
        role: khulnasoft_cluster_master
        tier: management 
    spec:
      hostname: master
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - indexer.khulnasoft.svc.cluster.local
      containers:
        - name: master
          image: khulnasoft/khulnasoft:latest
          env:
            - name: KHULNASOFT_HOME
              value: /opt/khulnasoft
            - name: KHULNASOFT_DEFAULTS_URL
              value: http://khulnasoft-defaults/default.yml
            - name: KHULNASOFT_ROLE
              value: khulnasoft_cluster_master
            - name: KHULNASOFT_PASSWORD
              value: helloworld
            - name: KHULNASOFT_START_ARGS
              value: "--accept-license"
            - name: KHULNASOFT_CLUSTER_MASTER_URL
              value: master
            - name: KHULNASOFT_INDEXER_URL
              value: indexer-0,indexer-1,indexer-2 
            - name: KHULNASOFT_SEARCH_HEAD_URL
              value: search
            - name: DEBUG
              value: "true"
          ports:
            - name: web
              containerPort: 8000
            - name: mgmt
              containerPort: 8089
            - name: kv
              containerPort: 8191
          volumeMounts: 
            - name: khulnasoft-master-data
              mountPath: /opt/khulnasoft/var
            - name: khulnasoft-master-config
              mountPath: /opt/khulnasoft/etc
      volumes:
        - name: khulnasoft-master-config
          emptyDir: {}
        - name: khulnasoft-master-data
          emptyDir: {}
