version: "3.6"

networks:
  khulnasoftnet:
    driver: bridge
    attachable: true

services:
  appserver:
    networks:
      khulnasoftnet:
        aliases:
          - appserver
    image: nwang92/nginx-mitm
    hostname: appserver
    ports:
      - 80
    volumes:
      - ../tests/fixtures:/www/data

  depserver1:
    networks:
      khulnasoftnet:
        aliases:
          - depserver1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: depserver1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_ROLE=khulnasoft_deployment_server
      - KHULNASOFT_APPS_URL
      - DEBUG=true
      - KHULNASOFT_PASSWORD
    ports:
      - 8089

  so1:
    networks:
      khulnasoftnet:
        aliases:
          - so1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: so1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_DEPLOYMENT_SERVER=depserver1
      - DEBUG=true
      - KHULNASOFT_PASSWORD
    ports:
      - 8000
      - 8089
