version: "3.6"

networks:
  khulnasoftnet:
    driver: bridge
    attachable: true
  
services:
  appserver:
    networks:
      khulnasoftnet:
        aliases:
          - appserver
    image: nwang92/nginx-mitm
    hostname: appserver
    ports:
      - 80
    volumes:
      - ../tests/fixtures:/www/data

  dep1:
    networks:
      khulnasoftnet:
        aliases:
          - dep1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: dep1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_INDEXER_URL=idx1
      - KHULNASOFT_SEARCH_HEAD_CAPTAIN_URL=sh1
      - KHULNASOFT_SEARCH_HEAD_URL=sh2,sh3
      - KHULNASOFT_DEPLOYER_URL=dep1
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_deployer
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
      - KHULNASOFT_PASSWORD
      - KHULNASOFT_DEFAULTS_URL
      - KHULNASOFT_APPS_URL
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  sh1:
    networks:
      khulnasoftnet:
        aliases:
          - sh1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: sh1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_INDEXER_URL=idx1
      - KHULNASOFT_SEARCH_HEAD_CAPTAIN_URL=sh1
      - KHULNASOFT_SEARCH_HEAD_URL=sh2,sh3
      - KHULNASOFT_DEPLOYER_URL=dep1
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_search_head
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
      - KHULNASOFT_PASSWORD
      - KHULNASOFT_DEFAULTS_URL
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  sh2:
    networks:
      khulnasoftnet:
        aliases:
          - sh2
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: sh2
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_INDEXER_URL=idx1
      - KHULNASOFT_SEARCH_HEAD_CAPTAIN_URL=sh1
      - KHULNASOFT_SEARCH_HEAD_URL=sh2,sh3
      - KHULNASOFT_DEPLOYER_URL=dep1
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_search_head
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
      - KHULNASOFT_PASSWORD
      - KHULNASOFT_DEFAULTS_URL
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  sh3:
    networks:
      khulnasoftnet:
        aliases:
          - sh3
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: sh3
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_INDEXER_URL=idx1
      - KHULNASOFT_SEARCH_HEAD_CAPTAIN_URL=sh1
      - KHULNASOFT_SEARCH_HEAD_URL=sh2,sh3
      - KHULNASOFT_DEPLOYER_URL=dep1
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_search_head
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
      - KHULNASOFT_PASSWORD
      - KHULNASOFT_DEFAULTS_URL
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  cm1:
    networks:
      khulnasoftnet:
        aliases:
          - cm1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: cm1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_INDEXER_URL=idx1
      - KHULNASOFT_SEARCH_HEAD_CAPTAIN_URL=sh1
      - KHULNASOFT_SEARCH_HEAD_URL=sh2,sh3
      - KHULNASOFT_DEPLOYER_URL=dep1
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_cluster_master
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
      - KHULNASOFT_PASSWORD
      - KHULNASOFT_DEFAULTS_URL
      - KHULNASOFT_APPS_URL
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  idx1:
    networks:
      khulnasoftnet:
        aliases:
          - idx1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: idx1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_INDEXER_URL=idx1
      - KHULNASOFT_SEARCH_HEAD_CAPTAIN_URL=sh1
      - KHULNASOFT_SEARCH_HEAD_URL=sh2,sh3
      - KHULNASOFT_DEPLOYER_URL=dep1
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_indexer
      - KHULNASOFT_APPS_URL
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
      - KHULNASOFT_PASSWORD
      - KHULNASOFT_DEFAULTS_URL
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults
