version: "3.6"

networks:
  khulnasoftnet:
    driver: bridge
    attachable: true

services:
  sh1:
    networks:
      khulnasoftnet:
        aliases:
          - sh1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: sh1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_search_head
      - KHULNASOFT_PASSWORD
      - DEBUG=true
    ports:
      - 8000
      - 8089

  cm1:
    networks:
      khulnasoftnet:
        aliases:
          - cm1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: cm1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_ROLE=khulnasoft_cluster_master
      - KHULNASOFT_PASSWORD
      - DEBUG=true
    ports:
      - 8000
      - 8089
