version: "3.6"

networks:
  khulnasoftnet:
    driver: bridge
    attachable: true

services:
  cm1:
    networks:
      khulnasoftnet:
        aliases:
          - cm1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: cm1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_ROLE=khulnasoft_cluster_master
      - DEBUG=true
      - KHULNASOFT_PASSWORD
    ports:
      - 8000
      - 8089

  so1:
    networks:
      khulnasoftnet:
        aliases:
          - so1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: so1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - DEBUG=true
      - KHULNASOFT_PASSWORD
    ports:
      - 8000
      - 8089
