version: "3.1"

networks:
  khulnasoftnet:
    driver: overlay 

services:
  so1:
    networks:
      khulnasoftnet:
        aliases:
          - so1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: so1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_LICENSE_URI=/run/secrets/khulnasoft_license
      - KHULNASOFT_PASSWORD
    ports:
      - 8000
      - 8089
    secrets:
      - khulnasoft_license
      
secrets:
    khulnasoft_license:
        external: true
