version: "3.6"

networks:
  khulnasoftnet:
    driver: bridge
    attachable: true

volumes:
  so1-etc:
  so1-var:

services:
  so1:
    networks:
      khulnasoftnet:
        aliases:
          - so1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_PASSWORD
      - DEBUG=true
    ports:
      - 8000
      - 8089
    volumes:
      - so1-etc:/opt/khulnasoft/etc
      - so1-var:/opt/khulnasoft/var
