version: "3.6"

networks:
  khulnasoftnet:
    driver: bridge
    attachable: true

services:
  uf1:
    image: ${UF_IMAGE:-khulnasoft/universalforwarder:latest}
    hostname: uf1
    container_name: uf1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_PASSWORD
      - DEBUG=true
    ports:
      - 8089