version: "3.6"

networks:
  khulnasoftnet:
    driver: bridge
    attachable: true

services:
  uf1:
    networks:
      khulnasoftnet:
        aliases:
          - uf1
    image: ${UF_IMAGE:-khulnasoft/universalforwarder:latest}
    hostname: uf1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_STANDALONE_URL=so1
      - DEBUG=true
      - KHULNASOFT_ADD=udp 1514,monitor /var/log/*
      - KHULNASOFT_PASSWORD
    ports:
      - 8089

  so1:
    networks:
      khulnasoftnet:
        aliases:
          - so1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    hostname: so1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_STANDALONE_URL=so1
      - DEBUG=true
      - KHULNASOFT_PASSWORD
    ports:
      - 8000
      - 8089
