version: "3.6"

networks:
  khulnasoftnet:
    driver: bridge
    attachable: true

services:
  uf1:
    networks:
      khulnasoftnet:
        aliases:
          - uf1
    image: ${UF_IMAGE:-khulnasoft/universalforwarder:latest}
    hostname: uf1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_PASSWORD
      - KHULNASOFT_HEC_TOKEN=abcd1234
      - DEBUG=true
    ports:
      - 8089
      - 8088
