version: "3.6"

networks:
  khulnasoftnet:
    driver: bridge
    attachable: true

services:
  so1:
    networks:
      khulnasoftnet:
        aliases:
          - so1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    command: start
    hostname: so1
    container_name: so1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_STANDALONE_URL=so1,so2
      - KHULNASOFT_HEAVY_FORWARDER_URL=hf1,hf2
      - KHULNASOFT_ROLE=khulnasoft_standalone
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  so2:
    networks:
      khulnasoftnet:
        aliases:
          - so2
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    command: start
    hostname: so2
    container_name: so2
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_STANDALONE_URL=so1,so2
      - KHULNASOFT_HEAVY_FORWARDER_URL=hf1,hf2
      - KHULNASOFT_ROLE=khulnasoft_standalone
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  so2:
    networks:
      khulnasoftnet:
        aliases:
          - so2
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    command: start
    hostname: so2
    container_name: so2
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_STANDALONE_URL=so1,so2
      - KHULNASOFT_HEAVY_FORWARDER_URL=hf1,hf2
      - KHULNASOFT_ROLE=khulnasoft_standalone
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults
      

  hf1:
    networks:
      khulnasoftnet:
        aliases:
          - hf1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    command: start
    hostname: hf1
    container_name: hf1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_STANDALONE_URL=so1,so2
      - KHULNASOFT_HEAVY_FORWARDER_URL=hf1,hf2
      - KHULNASOFT_ROLE=khulnasoft_heavy_forwarder
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  hf2:
    networks:
      khulnasoftnet:
        aliases:
          - hf2
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    command: start
    hostname: hf2
    container_name: hf2
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_STANDALONE_URL=so1,so2
      - KHULNASOFT_HEAVY_FORWARDER_URL=hf1,hf2
      - KHULNASOFT_ROLE=khulnasoft_heavy_forwarder
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults
