version: "3.6"

networks:
  khulnasoftnet:
    driver: bridge
    attachable: true

services:
  cm1:
    networks:
      khulnasoftnet:
        aliases:
          - cm1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    command: start
    hostname: cm1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_INDEXER_URL=idx1,idx2,idx3
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_cluster_master
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
      - KHULNASOFT_PASSWORD
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  idx1:
    networks:
      khulnasoftnet:
        aliases:
          - idx1
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    command: start
    hostname: idx1
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_INDEXER_URL=idx1,idx2,idx3
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_indexer
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
      - KHULNASOFT_PASSWORD
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  idx2:
    networks:
      khulnasoftnet:
        aliases:
          - idx2
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    command: start
    hostname: idx2
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_INDEXER_URL=idx1,idx2,idx3
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_indexer
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
      - KHULNASOFT_PASSWORD
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  idx3:
    networks:
      khulnasoftnet:
        aliases:
          - idx3
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    command: start
    hostname: idx3
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_INDEXER_URL=idx1,idx2,idx3
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_indexer
      - KHULNASOFT_LICENSE_URI
      - DEBUG=true
      - KHULNASOFT_PASSWORD
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  dmc:
    networks:
      khulnasoftnet:
        aliases:
          - dmc
    image: ${KHULNASOFT_IMAGE:-khulnasoft/khulnasoft:latest}
    command: start
    hostname: dmc
    environment:
      - KHULNASOFT_START_ARGS=--accept-license
      - KHULNASOFT_CLUSTER_MASTER_URL=cm1
      - KHULNASOFT_ROLE=khulnasoft_monitor
      - KHULNASOFT_LICENSE_URI
      - KHULNASOFT_PASSWORD
      - DEBUG=true
    ports:
      - 8000
      - 8089