---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: khulnasoft-license-data
  labels:
    app: khulnasoft
    role: khulnasoft_license_master
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: khulnasoft-license-config
  labels:
    app: khulnasoft
    role: khulnasoft_license_master
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

