---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: captain
  labels:
    app: khulnasoft
    role: khulnasoft_search_head_captain
    tier: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khulnasoft
      role: khulnasoft_search_head_captain
      tier: search
  template:
    metadata:
      labels:
        app: khulnasoft
        role: khulnasoft_search_head_captain
        tier: search
    spec:
      hostname: captain
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - indexer.khulnasoft.svc.cluster.local
          - search.khulnasoft.svc.cluster.local
      containers:
        - name: captain
          image: khulnasoft/khulnasoft:latest
          env:
            - name: KHULNASOFT_HOME
              value: /opt/khulnasoft
            - name: KHULNASOFT_DEFAULTS_URL
              value: http://khulnasoft-defaults/default.yml
            - name: KHULNASOFT_ROLE
              value: khulnasoft_search_head_captain
            - name: KHULNASOFT_PASSWORD
              value: helloworld
            - name: KHULNASOFT_START_ARGS
              value: "--accept-license"
            - name: KHULNASOFT_CLUSTER_MASTER_URL
              value: master
            - name: KHULNASOFT_INDEXER_URL
              value: indexer-0,indexer-1,indexer-2 
            - name: KHULNASOFT_SEARCH_HEAD_URL
              value: search-0,search-1 
            - name: KHULNASOFT_DEPLOYER_URL
              value: deployer
            - name: KHULNASOFT_SEARCH_HEAD_CAPTAIN_URL
              value: captain
            - name: DEBUG
              value: "true"
          ports:
            - name: web
              containerPort: 8000
            - name: mgmt
              containerPort: 8089
            - name: shc
              containerPort: 4001
            - name: kv 
              containerPort: 8191
          volumeMounts:
            - name: khulnasoft-captain-data
              mountPath: /opt/khulnasoft/var
            - name: khulnasoft-captain-config
              mountPath: /opt/khulnasoft/etc
      volumes:
        - name: khulnasoft-captain-config
          persistentVolumeClaim:
            claimName: khulnasoft-captain-config
        - name: khulnasoft-captain-data
          persistentVolumeClaim:
            claimName: khulnasoft-captain-data
