---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: khulnasoft-captain-data
  labels:
    app: khulnasoft
    role: khulnasoft_search_head_captain
    tier: search
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: khulnasoft-captain-config
  labels:
    app: khulnasoft
    role: khulnasoft_search_head_captain
    tier: search
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

