---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: khulnasoft-deployer-data
  labels:
    app: khulnasoft
    role: khulnasoft_deployer
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: khulnasoft-deployer-config
  labels:
    app: khulnasoft
    role: khulnasoft_deployer
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

