---
apiVersion: v1
kind: Service
metadata:
  name: master
  labels:
    app: khulnasoft
    role: khulnasoft_cluster_master
    tier: management 
spec:
  selector:
    app: khulnasoft
    role: khulnasoft_cluster_master
    tier: management
  ports:
    - name: khulnasoftweb
      port: 8000
      targetPort: 8000
    - name: khulnasoftd
      port: 8089
      targetPort: 8089
  clusterIP: None
