---
apiVersion: v1
kind: Service
metadata:
  name: deployer 
  labels:
    app: khulnasoft
    role: khulnasoft_deployer
    tier: management 
spec:
  selector:
    app: khulnasoft
    role: khulnasoft_deployer
    tier: management
  ports:
    - name: khulnasoftweb
      port: 8000
      targetPort: 8000
    - name: khulnasoftd
      port: 8089
      targetPort: 8089
    - name: kv
      port: 8191
      targetPort: 8191
  clusterIP: None
