---
apiVersion: v1
kind: Service
metadata:
  name: captain
  labels:
    app: khulnasoft
    role: khulnasoft_search_head_captain
    tier: search 
spec:
  selector:
    app: khulnasoft
    role: khulnasoft_search_head_captain
    tier: search
  ports:
    - name: khulnasoftweb
      port: 8000
      targetPort: 8000
    - name: khulnasoftd
      port: 8089
      targetPort: 8089
    - name: replication 
      port: 4001 
      targetPort: 4001
    - name: kv 
      port: 8191
      targetPort: 8191
  clusterIP: None
