---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: khulnasoft-search-data
  labels:
    app: khulnasoft
    role: khulnasoft_search_head
    tier: search
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: khulnasoft-search-config
  labels:
    app: khulnasoft
    role: khulnasoft_search_head
    tier: search
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

