---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: khulnasoft
    role: khulnasoft_search_head
    tier: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khulnasoft
      role: khulnasoft_search_head
      tier: search
  template:
    metadata:
      labels:
        app: khulnasoft
        role: khulnasoft_search_head
        tier: search
    spec:
      hostname: search
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - indexer.khulnasoft.svc.cluster.local
      containers:
        - name: search
          image: khulnasoft/khulnasoft:latest
          env:
            - name: KHULNASOFT_HOME
              value: /opt/khulnasoft
            - name: KHULNASOFT_DEFAULTS_URL
              value: http://khulnasoft-defaults/default.yml
            - name: KHULNASOFT_ROLE
              value: khulnasoft_search_head
            - name: KHULNASOFT_PASSWORD
              value: helloworld
            - name: KHULNASOFT_START_ARGS
              value: "--accept-license"
            - name: KHULNASOFT_CLUSTER_MASTER_URL
              value: master
            - name: KHULNASOFT_INDEXER_URL
              value: indexer-0,indexer-1,indexer-2
            - name: KHULNASOFT_SEARCH_HEAD_URL
              value: search
            - name: DEBUG
              value: "true"
          ports:
            - name: web
              containerPort: 8000
            - name: mgmt
              containerPort: 8089
            - name: kv
              containerPort: 8191
          volumeMounts:
            - name: khulnasoft-search-data
              mountPath: /opt/khulnasoft/var
            - name: khulnasoft-search-config
              mountPath: /opt/khulnasoft/etc
      volumes:
        - name: khulnasoft-search-config
          persistentVolumeClaim:
            claimName: khulnasoft-search-config
        - name: khulnasoft-search-data
          persistentVolumeClaim:
            claimName: khulnasoft-search-data
