---
apiVersion: v1
kind: Service
metadata:
  name: indexer 
  labels:
    app: khulnasoft
    role: khulnasoft_indexer
    tier: indexer 
spec:
  selector:
    app: khulnasoft
    role: khulnasoft_indexer
    tier: indexer
  ports:
    - name: khulnasoftweb
      port: 8000
      targetPort: 8000
    - name: khulnasoftd
      port: 8089
      targetPort: 8089
    - name: replication
      port: 4001 
      targetPort: 4001
    - name: s2s
      port: 9997
      targetPort: 9997
  clusterIP: None
